### ISSUE TITLE
KeyError: 'cuda_version'

### ISSUE THREAD

**Issue by kwwcv** [zmyme/gpuutil#1]
After 
pip install https://git.zmy.pub/zmyme/gpuutil/archive/v0.0.3.tar.gz
I directly run
python -m gpuutil,
but get error below:

Traceback (most recent call last):
  File "/home/wangkewei/anaconda3/envs/pytorchenv/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/wangkewei/anaconda3/envs/pytorchenv/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wangkewei/anaconda3/envs/pytorchenv/lib/python3.6/site-packages/gpuutil/__main__.py", line 112, in <module>
    stat.show(enabled_cols = cols, colsty=style, colsz=limit, vertical=vertical, show_command=show_process)
  File "/home/wangkewei/anaconda3/envs/pytorchenv/lib/python3.6/site-packages/gpuutil/gpuutil.py", line 303, in show
    self.parse()
  File "/home/wangkewei/anaconda3/envs/pytorchenv/lib/python3.6/site-packages/gpuutil/gpuutil.py", line 288, in parse
    "cuda_version": self.detailed_info["cuda_version"],
KeyError: 'cuda_version'

Additionaly, my cuda version is 8.0.

**Comment by zmyme** [comment]
that might be due to the different output between different nvidia-smi versions, this issue is resolved in [#2685e207](https://github.com/zmyme/gpuutil/commit/2685e20782fcf858e2cc1e3e0378afa21e6a5b3c), re-install the package now should give you correct output.
